// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQHdh5UKj4QwYEfzVybd22blRy2Dv71t4',
    appId: '1:387423625888:web:b70920170812d75c291fc5',
    messagingSenderId: '387423625888',
    projectId: 'mashov-9c3e8',
    authDomain: 'mashov-9c3e8.firebaseapp.com',
    storageBucket: 'mashov-9c3e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbLKMdFhRkR48DhknQTvAxDC_XROgMeOQ',
    appId: '1:387423625888:android:f2b7f83a181d6ba5291fc5',
    messagingSenderId: '387423625888',
    projectId: 'mashov-9c3e8',
    storageBucket: 'mashov-9c3e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChQlEncguYD3w-nV0MGAjCC3pxgXJgfY8',
    appId: '1:387423625888:ios:d9c617bd01bed4c7291fc5',
    messagingSenderId: '387423625888',
    projectId: 'mashov-9c3e8',
    storageBucket: 'mashov-9c3e8.appspot.com',
    iosClientId: '387423625888-81hia0pmkeqke548kvl066505fk579em.apps.googleusercontent.com',
    iosBundleId: 'com.example.mashov',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChQlEncguYD3w-nV0MGAjCC3pxgXJgfY8',
    appId: '1:387423625888:ios:d9c617bd01bed4c7291fc5',
    messagingSenderId: '387423625888',
    projectId: 'mashov-9c3e8',
    storageBucket: 'mashov-9c3e8.appspot.com',
    iosClientId: '387423625888-81hia0pmkeqke548kvl066505fk579em.apps.googleusercontent.com',
    iosBundleId: 'com.example.mashov',
  );
}
